name: flutter_map_cache_example
description: An example app for the flutter_map_cache package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map_cache:
    path: ../
  #flutter_map: ^6.0.0-dev.2
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: tile-provider-improvements
  latlong2: ^0.9.0
  connectivity_plus: ^4.0.1
  path_provider: ^2.0.15
  dio: ^5.2.0+1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_db_store: ^5.1.0
  dio_cache_interceptor_file_store: ^1.2.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dio_cache_interceptor_objectbox_store: ^1.1.1
  dio_cache_interceptor_sembast_storage: ^0.1.0
  objectbox_flutter_libs: ^1.4.1 # ObjectBox
  sqlite3_flutter_libs: ^0.5.15 # Drift

dev_dependencies:
  flutter_test:
    sdk: flutter
  total_lints: ^3.0.0

flutter:
  uses-material-design: true
