name: flutter_map_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/josxha/flutter_map_cache
authors:
  - josxha
issue_tracker:

environment:
  sdk: ^3.0.1

dependencies:
  dio_cache_interceptor: ^3.4.2
  dio: ^5.2.0+1

dev_dependencies:
  total_lints: ^3.0.0
