name: flutter_map_cache
description: A slim yet powerful caching plugin for flutter_map tile layers.
version: 1.2.0
repository: https://github.com/josxha/flutter_map_cache
issue_tracker: https://github.com/josxha/flutter_map_cache/issues
publish_to: none # remove this line when dependency_overrides are removed

topics: [ flutter-map, map, dio, cache ]

environment:
  sdk: ^3.0.1

dependencies:
  flutter:
    sdk: flutter
  dio_cache_interceptor: ^3.4.2
  dio: ^5.2.0+1
  flutter_map: ^5.0.0

dev_dependencies:
  total_lints: ^3.0.0

dependency_overrides:
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: c7c6bd01ca694372ea89d953564407a7b0d31b7d