name: Build Android
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
